### ISSUE TITLE
Responsive menu cannot be opened twice and the last item overflows

### ISSUE THREAD

**Issue by MikkCZ** [mozillaslovenija/mozilla.si#1]
STR:

1. Visit mozilla.si on a mobile phone (testes Nightly for Android).
2. Tap the hamburger icon - menu will open. Notice the last menu item overflows the "tooltip" background.
3. Tap the hamburger icon again - menu will close.
4. Tap the hamburger icon for the third time - menu should open again, but does not.

**Comment by MikkCZ** [comment]
@lucashir may I help you with this, or are you already in stage of planning for the new Moz://a design?

**Comment by lucashir** [comment]
Hello, 
Thank you for your feedback. We have some planes in place to upgrade to a new design. Waiting for an slot to do so.

**Comment by MikkCZ** [comment]
There was top menu added directly into One-Mozilla-blog back in 2016. https://github.com/mozilla/One-Mozilla-blog/issues/35

**Comment by MikkCZ** [comment]
Given the low activity here and on Mozilla.si, I am closing this to clear up my list of open issues. Feel free to reopen or file a new issue, however shall Mozilla.si be revived, I would advise go to for some new Moz://a style theme anyway.
